### ISSUE TITLE
App UI initial impressions

### ISSUE THREAD

**Issue by winder** [npenkov/pebslee-pebble#3]
When I tried your app for the first time there were parts of the UI which weren't very intuitive for me. In case you find these initial impressions useful, here they are.
1. The long vs. short button presses. I like this feature while tracking is enabled, but before I realized it was a feature it made the app feel sluggish.
2. The middle button has different actions for long/short presses. I don't like having to remember what buttons do, since the alarm is already available from the configure menu I would just remove the short press here.
3. "Start tracking" vs "track sleep" both sound like actions rather than states. My first time using the app I started and stopped it several times because I wasn't sure it was tracking. Maybe "start tracking" and "stop tracking" would be clearer. Even better would be an intermediate window after you start tracking that says tracking was started before going back to the main window.
4. The companion app was intuitive enough, I had zero issues syncing data unlike the alternative sleep tracking apps I tried. That's my most important feature, so I'm very happy about that!
5. In the stats window there are button triangles on the right even though those buttons don't do anything.

Thanks for all your work on this!

**Comment by npenkov** [comment]
Hi,

1 - Have you check the www.pebslee.com/www.pinsleep.mobi - I think I have put there some explanation about the long clicks. If not, may be it is a good area of improvement

2 - makes sense. Initially there was no configuration options, that is why the short click is there - I will definitely remove it.

3 - luckily this is easily adjustable via translations bundle.  
1. "In the stats window there are button triangles on the right even though those buttons don't do anything.” - they do - when you have up to ten days of history, with up and down button you can navigate and see the stats for previous days. Maybe it is a good idea to hide the buttons, where there is nothing to navigate to (no history)

Notes taken.
Thanks a lot for the suggestions!

Cheers,
Nick
